### PR TITLE
Add conversation record snippet

### PR DESCRIPTION
**Pull request by timcraft**
References #59

### CODE REVIEW

**Comment by benhayehudi** [comment]
Hi @timcraft,

I've tried running this snippet providing it with a `conversation_id` for an active conversation, and with the rest of the relevant details for the application, both ID and private key, along with the api credentials, but I am getting back a `Nexmo::ClientError` referencing line 115 in the `/lib/namespace.rb`, which is the parsing for errors. 

Did you try to run this snippet? If so, was it working for you? Also, this makes me think that maybe it would be worthwhile to return more descriptive errors to the user in examples such as these?

Thanks,

Ben

**Comment by benhayehudi** [comment]
> @benhayehudi A client error is usually due to a missing or invalid parameter. Can you try with a debug logger to see what's the HTTP response is? You can set the logger like this:
> 
> ```
>   require 'logger'
> 
>   logger = Logger.new(STDOUT, level: Logger::DEBUG)
> 
>   client = Nexmo::Client.new(logger: logger)
> ```
> 
> No I didn't run the snippet. Descriptive errors are useful and the SDK returns them where possible, but the server won't always return something descriptive.

Hi @timcraft,

The error returned is:

```
{"code":"http:error:not-found","description":"Endpoint does not exist, or you do not have access."}
```

I'm not sure that makes sense though as I checked the code and the endpoint provided in the gem is correct according to the docs, which is `https://api.nexmo.com/beta/conversations/:conversation_id/record`.

**Comment by benhayehudi** [comment]
Hi @timcraft,

Working on debugging this issue. The first thing is I forgot because I hadn't needed to do it in a while, but in parts of the world, like where I live, I need to manually specify my API host, otherwise, I can't hit the endpoint. Currently, that means overriding the `host` with calling `client.conversations.instance_variable_set(:@host, 'api-us-1.nexmo.com')`, but even when doing that, the API is returning a 404 to me for the Conversation. I'll probably not be able to wrap this up this afternoon, but I'll get back on it early next week.

Have a good weekend,

Ben

**Comment by timcraft** [comment]
> Working on debugging this issue. The first thing is I forgot because I hadn't needed to do it in a while, but in parts of the world, like where I live, I need to manually specify my API host

If you have a proxy you can use then you can specify proxy settings using the http option, not sure if that'll be easier overall. Or can you use a VPN to connect from elsewhere?

> but even when doing that, the API is returning a 404 to me for the Conversation. I'll probably not be able to wrap this up this afternoon, but I'll get back on it early next week.

If you can share the snippet you're using to setup the state/context for the conversation I can run that locally to see if I get the same 404 response.

**Comment by benhayehudi** [comment]
Hi @timcraft, the issue has been identified. The endpoint for recording a conversation is actually `https://api.nexmo.com/v1/conversations/:conversation_id/record`. The gem will need to be updated to account for that. I'll be raising a PR in the API docs to do the same.

**Comment by benhayehudi** [comment]
Thanks, @timcraft for the exploration of this together. I've confirmed that the snippet now works as intended! Always a pleasure. Have a good rest of the week.

**Pull request merged**
