### PR TITLE
Require dotenv/load

### PR DESCRIPTION
**Pull request by timcraft**
Eliminates the calls to `Dotenv.load` and shortens the code snippets.

### CODE REVIEW

**Comment by benhayehudi** [comment]
Hi @timcraft,

Thanks for this. All of these changes alter the line numbers in the Ruby YAML files in NDP under `/_examples/` which are used to generate the code snippets on the site. 

An accompanying PR is required to be opened on NDP that alters those YAML files with the new line numbers for both `code` and `client` sections. This can't be merged until that one is ready.

Thanks again,

Ben

**Comment by timcraft** [comment]
> An accompanying PR is required to be opened on NDP that alters those YAML files with the new line numbers for both `code` and `client` sections.

Ok thanks, that seems rather fragile and inflexible.

Closing for now.

**Comment by mheap** [comment]
I’d like to see this change made and the lines updated as it simplifies things

@benhayehudi Could you take care of the NDP side of things? It’s mechanical work, but it’s valuable

**Comment by timcraft** [comment]
I had at least one other follow up simplification in mind, updating the line numbers manually for every change like this seems like a big potential source of error (or stagnation).

What do you think about adding some kind of rake command to increment/decrement all line numbers for a given language? If it's a mechanical change it should be easy enough to automate?

**Comment by mheap** [comment]
Updating every file like this is an infrequent task, so I’m not sure that
adding code that needs maintaining is the correct solution here

I wouldn’t say no to a rake task, but I also wouldn’t be jumping to build
one either

**Comment by benhayehudi** [comment]
Tim, can you reopen this with your other follow up simplification as well. If it alters the line numbers, I'd rather go through making that change once.

**Comment by timcraft** [comment]
> Tim, can you reopen this with your other follow up simplification as well. If it alters the line numbers, I'd rather go through making that change once.

The follow up change I was thinking of is moving the `require 'nexmo'` lines up so all the requires are together, but it's not clear if that line meant to be shown as part of the code snippet or not? For example the "List all secrets" snippet includes the line (in the "Initialize your dependencies" section), but the other secrets snippets don't include it.

**Comment by benhayehudi** [comment]
The way the Ruby snippets were originally written was to group the `require` statements with their accompanying code. I kept it in that format as I added new snippets. @mheap, what are your thoughts? I'd recommend leaving it as is.

**Comment by mheap** [comment]
I'm a fan of keeping all the `require` statements together at the top so that you can see the file's dependencies at a glance

**Comment by timcraft** [comment]
> I'm a fan of keeping all the `require` statements together at the top so that you can see the file's dependencies at a glance

Yep that's the motivation, it's much easier to review at a glance.

I'll re-open with both changes and then you can merge as you see fit.

**Comment by benhayehudi** [comment]
I am as well, but I also was hesitant to change the convention for the
snippets that I inherited. Glad to see this change.

**Pull request closed without merging**
